-- SQL Schema for Bluestar KitchenHub Agent Onboarding
-- Copy and run this in your Supabase SQL Editor.

-- 1. Create Agents Table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.agents (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    login_id TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Applications Table
CREATE TABLE IF NOT EXISTS public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id UUID REFERENCES public.agents(id) ON DELETE CASCADE NOT NULL,
    experience_text TEXT,
    availability TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

-- 3. Create Downloads Table
CREATE TABLE IF NOT EXISTS public.downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id UUID REFERENCES public.agents(id) ON DELETE SET NULL,
    ip_address TEXT,
    browser TEXT,
    downloaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.downloads ENABLE ROW LEVEL SECURITY;

-- 5. Set up RLS Policies
-- Agents Policies
DROP POLICY IF EXISTS "Allow users to read their own agent profile" ON public.agents;
CREATE POLICY "Allow users to read their own agent profile"
ON public.agents FOR SELECT
TO authenticated
USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow users to insert their own agent profile" ON public.agents;
CREATE POLICY "Allow users to insert their own agent profile"
ON public.agents FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Allow users to update their own agent profile" ON public.agents;
CREATE POLICY "Allow users to update their own agent profile"
ON public.agents FOR UPDATE
TO authenticated
USING (auth.uid() = id);

-- Applications Policies
DROP POLICY IF EXISTS "Allow users to read their own application" ON public.applications;
CREATE POLICY "Allow users to read their own application"
ON public.applications FOR SELECT
TO authenticated
USING (auth.uid() = agent_id);

DROP POLICY IF EXISTS "Allow users to insert their own application" ON public.applications;
CREATE POLICY "Allow users to insert their own application"
ON public.applications FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = agent_id);

-- Downloads Policies
DROP POLICY IF EXISTS "Allow users to read their own downloads" ON public.downloads;
CREATE POLICY "Allow users to read their own downloads"
ON public.downloads FOR SELECT
TO authenticated
USING (auth.uid() = agent_id);

DROP POLICY IF EXISTS "Allow users to insert their own downloads" ON public.downloads;
CREATE POLICY "Allow users to insert their own downloads"
ON public.downloads FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = agent_id);

-- 6. Create check_and_approve_agent function (SECURITY DEFINER)
-- This function runs with database owner privileges to safely auto-approve
-- agents after 3 hours and generate their unique login ID.
CREATE OR REPLACE FUNCTION public.check_and_approve_agent(agent_uuid UUID)
RETURNS SETOF public.agents
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    agent_record public.agents;
    rand_id TEXT;
    id_exists BOOLEAN;
    is_force_approve BOOLEAN;
BEGIN
    -- Get current agent record
    SELECT * INTO agent_record FROM public.agents WHERE id = agent_uuid;
    
    -- If agent doesn't exist, return empty
    IF agent_record.id IS NULL THEN
        RETURN;
    END IF;
    
    -- Check if there's a force-approve flag in the application text
    SELECT EXISTS (
        SELECT 1 FROM public.applications 
        WHERE agent_id = agent_uuid 
        AND (experience_text ILIKE '%force-approve%' OR availability ILIKE '%force-approve%')
    ) INTO is_force_approve;

    -- Check if agent is pending and registered for more than 3 hours (or force-approve for testing)
    IF agent_record.status = 'pending' AND (agent_record.created_at <= NOW() - INTERVAL '3 hours' OR is_force_approve) THEN
        -- Generate unique login_id (BSK-AG-XXXXX)
        LOOP
            rand_id := 'BSK-AG-' || LPAD(FLOOR(RANDOM() * 100000)::TEXT, 5, '0');
            SELECT EXISTS(SELECT 1 FROM public.agents WHERE login_id = rand_id) INTO id_exists;
            EXIT WHEN NOT id_exists;
        END LOOP;
        
        -- Update agent status and login_id
        UPDATE public.agents
        SET status = 'approved', login_id = rand_id
        WHERE id = agent_uuid
        RETURNING * INTO agent_record;
        
        -- Update application status
        UPDATE public.applications
        SET status = 'approved', reviewed_at = NOW()
        WHERE agent_id = agent_uuid;
    END IF;
    
    RETURN NEXT agent_record;
END;
$$;

-- 7. Create Tickets Table
CREATE TABLE IF NOT EXISTS public.tickets (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    agent_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    admin_status TEXT NOT NULL DEFAULT 'pending' CHECK (admin_status IN ('pending', 'approved', 'declined')),
    admin_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS on Tickets
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Tickets Policies
DROP POLICY IF EXISTS "Allow public select on tickets" ON public.tickets;
CREATE POLICY "Allow public select on tickets" ON public.tickets FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on tickets" ON public.tickets;
CREATE POLICY "Allow public insert on tickets" ON public.tickets FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on tickets" ON public.tickets;
CREATE POLICY "Allow public update on tickets" ON public.tickets FOR UPDATE USING (true);

-- 8. Create verify_agent_login function (SECURITY DEFINER)
-- This function runs with database owner privileges to safely verify agent login IDs
-- and return their basic profile including availability from the application.
CREATE OR REPLACE FUNCTION public.verify_agent_login(input_login_id TEXT)
RETURNS TABLE (
    id UUID,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    status TEXT,
    login_id TEXT,
    created_at TIMESTAMPTZ,
    availability TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a.id, 
        a.full_name, 
        a.email, 
        a.phone, 
        a.status, 
        a.login_id, 
        a.created_at,
        ap.availability
    FROM public.agents a
    LEFT JOIN public.applications ap ON a.id = ap.agent_id
    WHERE a.login_id = input_login_id AND a.status = 'approved'
    ORDER BY ap.created_at DESC
    LIMIT 1;
END;
$$;

